- apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
- apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    state: present
- name: Add NodeSource Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_4.x trusty main
    state: present
- name: Add MOAR repositories
  apt_repository: repo={{ item }}
  with_items: apt_ppas
- name: Update cache and upgrade
  apt: update_cache=yes upgrade=safe
- name: Install missing packages
  apt: name={{ item }}
  with_items: apt_packages
- name: Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose mode=0755
- name: Set default shell for {{ vm_user }} user
  user: name={{ vm_user }} shell=/usr/bin/fish groups=docker append=yes
- gem: name=tmuxinator state=present user_install=no
- gem: name=homesick state=present user_install=no
- name: Symlink dotfiles
  command: homesick link {{ item }} --force
  become: yes
  become_user: "{{ vm_user }}"
  with_items:
  - public
  - private
