- name: Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
- name: Add user to the Docker group
  user: name={{ ansible_ssh_user }} groups=docker append=yes
