- name: Add NodeSource Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_4.x xenial main
    state: present
- name: Add MOAR repositories
  apt_repository: repo={{ item }}
  with_items: "{{ apt_ppas }}"
- name: Install missing packages
  apt: name={{ item }} install_recommends=yes update_cache=yes
  with_items: "{{ apt_packages }}"
- name: Set default shell for {{ vm_user }} user
  user: name={{ vm_user }} shell=/usr/bin/fish groups=docker append=yes
- gem: name=tmuxinator state=present user_install=no
- gem: name=homesick state=present user_install=no
- stat: path=/dev/vdb
  register: code_disk
- name: Mount Code Volume
  mount: name=/home/bascht/Code src='/dev/vdb' fstype=ext4 state=mounted
  when: code_disk.stat.isblk is defined and code_disk.stat.isblk
- lineinfile: dest=/etc/exports line="/home/bascht/Code 192.168.0.0/16(rw,sync)"
- file:
    path: "/home/{{vm_user}}/.local/share/fonts/"
    state: directory
    mode: 0755
    owner: "{{ vm_user }}"
    group: "{{ vm_user }}"
- get_url:
    url=https://github.com/madmalik/mononoki/releases/download/1.2/mononoki.zip
    dest=/usr/local/src/mononoki.zip
    sha256sum=cf29ea7663dbfe94feaedaf5c0be4f4ae6a5b98c1293e0e772e69c28ac5dc658
- unarchive:
    src=/usr/local/src/mononoki.zip
    dest="/home/{{vm_user}}/.local/share/fonts/"
    copy=no
    creates="/home/{{vm_user}}/.local/share/fonts/mononoki-Regular.ttf"
    owner="{{ vm_user }}"
    group="{{ vm_user }}"
- name: "Clone Prelude"
  git: repo=https://github.com/bbatsov/prelude.git dest=/home/bascht/.emacs.d update=no clone=yes
  become_user: "{{ vm_user }}"
- name: "Clone Dotfiles"
  git: repo=https://github.com/bascht/dotfiles-public.git dest=/home/bascht/.homesick/repos/public update=no
  become_user: "{{ vm_user }}"
- name: "Symlink dotfiles"
  command: homesick link public --force
  become: yes
  become_user: "{{ vm_user }}"
- hostname:
    name: "{{ vm_hostname }}"
