- apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
- name: Add Docker Repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present
- name: Add NodeSource Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_4.x xenial main
    state: present
- name: Add MOAR repositories
  apt_repository: repo={{ item }}
  with_items: apt_ppas
- name: Install missing packages
  apt: name={{ item }}
  with_items: apt_packages
- name: Set default shell for {{ vm_user }} user
  user: name={{ vm_user }} shell=/usr/bin/fish groups=docker append=yes
- gem: name=tmuxinator state=present user_install=no
- gem: name=homesick state=present user_install=no
- git: repo=https://github.com/bbatsov/prelude.git dest=/home/bascht/.local/prelude
- mount: name=/home/bascht/Code src='/dev/vdb' fstype=ext4 state=mounted
- lineinfile: dest=/etc/exports line="/home/bascht/Code 192.168.0.0/16(rw,sync)"

#- name: Symlink dotfiles
#  command: homesick link {{ item }} --force
#  become: yes
#  become_user: "{{ vm_user }}"
#  with_items:
#  - public
#  - private
