- name: Set timezone
  timezone:
    name: Europe/Berlin
- name: Add NodeSource Signing Key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: Add NodeSource Repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x xenial main
    state: present
- name: Add MOAR repositories
  apt_repository: repo={{ item }}
  with_items: "{{ apt_ppas }}"
- name: Install missing packages
  apt: name={{ apt_packages }} install_recommends=yes update_cache=yes
- name: Set default shell for {{ vm_user }} user
  user:
    name: "{{ vm_user }}"
    shell: "/usr/bin/zsh"
    groups: docker
    append: true
    create_home: true
- stat: path=/dev/vda
  register: code_disk
- stat: path=/dev/vdb
  register: docker_disk
- stat: path=/home/{{vm_user}}/.gnupg/S.gpg-agent
  register: agent_socket
- name: Fix up SSH for proper Socket Forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'StreamLocalBindUnlink yes'
- name: Symlink Extra Agent Socket
  when: agent_socket.stat.exists == True
  file:
    src: "/home/{{vm_user}}/.gnupg/S.gpg-agent"
    dest: "/home/{{vm_user}}/.gnupg/S.gpg-agent.extra"
    state: link
    force: yes
- name: Symlink SSH Agent Socket
  when: agent_socket.stat.exists == True
  file:
    src: "/home/{{vm_user}}/.gnupg/S.gpg-agent"
    dest: "/home/{{vm_user}}/.gnupg/S.gpg-agent.ssh"
    state: link
    force: yes
- name: Mount Code Volume
  mount: name=/home/bascht/Code src='/dev/disk/by-id/virtio-code' fstype=ext4 state=mounted
  when: code_disk.stat.isblk is defined and code_disk.stat.isblk
- name: Mount Docker Volume
  mount: name=/var/lib/docker src='/dev/disk/by-id/virtio-docker' fstype=ext4 state=mounted
  when: docker_disk.stat.isblk is defined and docker_disk.stat.isblk
- lineinfile: dest=/etc/exports line="/home/bascht/Code 192.168.0.0/16(rw,sync)"
- name: Add baschts key
  authorized_key:
    user: "{{ vm_user }}"
    state: present
    key: "https://github.com/{{ vm_user }}.keys"
- hostname:
    name: "{{ vm_hostname }}"
