---
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
- apt: update_cache=yes name=docker-ce state=latest
