- get_url:
    url=https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip
    dest=/usr/local/src/packer.zip
    sha256sum=7d51fc5db19d02bbf32278a8116830fae33a3f9bd4440a58d23ad7c863e92e28
- unarchive:
    src=/usr/local/src/packer.zip
    dest=/usr/local/bin
    copy=no
    creates=/usr/local/bin/packer
- get_url:
    url=https://releases.hashicorp.com/terraform/0.7.0/terraform_0.7.0_linux_amd64.zip
    dest=/usr/local/src/terraform.zip
    sha256sum=a196c63b967967343f3ae9bb18ce324a18b27690e2d105e1f38c5a2d7c02038d
- unarchive:
    src=/usr/local/src/terraform.zip
    dest=/usr/local/bin
    copy=no
    creates=/usr/local/bin/terraform
- get_url:
    url=https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5_x86_64.deb
    dest=/usr/local/src/vagrant.deb
- apt:
    deb=/usr/local/src/vagrant.deb
