- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
- apt: update_cache=yes name=docker-ce state=latest

- gem: name=tmuxinator state=present user_install=no
- gem: name=pry state=present user_install=no
- gem: name=bundler state=present user_install=no
- stat: path=/home/bascht/.tmux.conf
  register: tmux_conf
- name: "Provide IP for Tmux + Shell to pick up"
  ignore_errors: yes
  copy:
    dest: /var/run/vm_ip
    mode: "0744"
    content: "{{ ansible_eth0.ipv4.address|default(omit) }}"
