- stat: path=/home/bascht/.tmux.conf
  register: tmux_conf
- name: "Provide IP for Tmux + Shell to pick up"
  ignore_errors: yes
  copy:
    dest: /var/run/vm_ip
    mode: "0744"
    content: "{{ ansible_eth0.ipv4.address|default(omit) }}"
- name: Install Tern globally
  npm:
    name: tern
    global: yes
