---
- hosts: all
  become: yes
  roles:
    - rvm_io.rvm1-ruby
    - franklinkim.docker
- hosts: all
  become: yes
  tasks:
  - include: tasks/base.yml
  - include: tasks/ruby.yml
  - include: tasks/docker.yml
  - include: tasks/hashitools.yml
