---
- hosts: all
  roles:
    - role: angstwad.docker_ubuntu
      become: yes
      docker_group_members:
        - bascht
      docker_opts: "-H tcp://0.0.0.0:2375"
- hosts: all
  become: yes
  tasks:
  - include: tasks/base.yml
  - include: tasks/tools.yml
  - include: tasks/docker.yml
  - include: tasks/hashitools.yml
